### ISSUE TITLE
npm ERR! Failed at the detox@15.5.0 postinstall script.

### ISSUE THREAD

**Issue by Avais392** [wix/react-native-calendars#1208]
## Description

Avaiss-MacBook-Pro:react-native-calendars-example-for-custom-container Avais$ npm install

> dtrace-provider@0.8.8 install /Users/Avais/Downloads/react-native-calendars-example-for-custom-container/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

  ACTION binding_gyp_ndtp_target_build_ndtp .
-----------------------------------------------------------------
Building dtrace-provider failed with exit code 1, falling back
on stub implementation.

Re-run install with V set in your environment to see the build
output, or NODE_DTRACE_PROVIDER_REQUIRE=hard to force an
installation failure.
-----------------------------------------------------------------
  TOUCH Release/obj.target/ndtp.stamp

> detox@15.5.0 postinstall /Users/Avais/Downloads/react-native-calendars-example-for-custom-container/node_modules/detox
> node scripts/postinstall.js

/Users/Avais/Library/Detox/ios/15e8b105e8e55208e939c4e06a3fa373383d3153 was found, but could not find Detox.framework inside it. This means that the Detox framework build process was interrupted.
         deleting /Users/Avais/Library/Detox/ios/15e8b105e8e55208e939c4e06a3fa373383d3153 and trying to rebuild.
Extracting Detox sources...
Building Detox.framework from /Users/Avais/Downloads/react-native-calendars-example-for-custom-container/node_modules/detox/ios_src...
child_process.js:632
    throw err;
    ^

Error: Command failed: /Users/Avais/Downloads/react-native-calendars-example-for-custom-container/node_modules/detox/scripts/build_framework.ios.sh
    at checkExecSyncError (child_process.js:611:11)
    at Object.execFileSync (child_process.js:629:15)
    at Object.<anonymous> (/Users/Avais/Downloads/react-native-calendars-example-for-custom-container/node_modules/detox/scripts/postinstall.js:2:27)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  status: 65,
  signal: null,
  output: [ null, null, null ],
  pid: 12466,
  stdout: null,
  stderr: null
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! detox@15.5.0 postinstall: `node scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the detox@15.5.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Avais/.npm/_logs/2020-06-23T12_19_21_338Z-debug.log

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:
react-native-calendars@1.22.0 /Users/Avais/Downloads/react-native-calendars-example-for-custom-container
└── (empty)

* `npm ls react-native`:
react-native-calendars@1.22.0 /Users/Avais/Downloads/react-native-calendars-example-for-custom-container
└── react-native@0.62.2 

## Reproducible Demo
I cloned the repo and did npm install.

**Comment by emilisb** [comment]
Please provide full error log. I could not reproduce this issue.

**Comment by GustavoContreiras-Feegow** [comment]
```
feegow@MacBook-Pro-de-Feegow feegow-app % yarn install
yarn install v1.22.10
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning @react-native-community/async-storage@1.12.1: Async Storage has moved to new organization: https://github.com/react-native-async-storage/async-storage
warning @react-native-community/async-storage > deep-assign@3.0.0: Check out `lodash.merge` or `merge-options` instead.
warning appcenter > appcenter-link-scripts > debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
warning appcenter > appcenter-link-scripts > mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning appcenter > appcenter-link-scripts > xcode > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning react-native > @react-native-community/cli-platform-ios > xcode > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning react-native > @react-native-community/cli > @hapi/joi@15.1.1: Switch to 'npm install joi'
warning react-native > @react-native-community/cli > @hapi/joi > @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
warning react-native > @react-native-community/cli > @hapi/joi > @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
warning react-native > @react-native-community/cli > @hapi/joi > @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
warning react-native > @react-native-community/cli > @hapi/joi > @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
warning react-native > @react-native-community/cli > @hapi/joi > @hapi/topo > @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
warning react-native > fbjs > core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
warning react-native > fbjs-scripts > core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
warning react-native > metro-babel-register > core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
warning react-native > @react-native-community/cli > metro-core > jest-haste-map > sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
warning react-native > @react-native-community/cli > metro-core > jest-haste-map > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning react-native > @react-native-community/cli > metro > metro-minify-uglify > uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0
warning react-native > @react-native-community/cli > metro-core > jest-haste-map > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning react-native > @react-native-community/cli > metro-core > jest-haste-map > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning react-native-voice@0.3.0: This module has been renamed to @react-native-community/voice. Updates will no longer be pushed to this package.
warning react-navigation@3.11.0: This version of React Navigation is no longer supported. Please upgrade to 4.x. Release notes: https://github.com/react-navigation/react-navigation/releases/tag/v4.0.0
warning react-navigation > react-navigation-stack@1.4.0: This version of React Navigation Stack is no longer supported. Please upgrade to 2.x.x. See https://reactnavigation.org/docs/4.x/upgrading-from-3.x#react-navigation-stack for instructions.
warning @react-native-community/eslint-config > babel-eslint@10.0.1: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()
warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > request > har-validator@5.1.5: this library is no longer supported
warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > styled-components@5.3.0" has unmet peer dependency "react-dom@>= 16.8.0".
warning " > styled-components@5.3.0" has unmet peer dependency "react-is@>= 16.8.0".
warning " > react-apollo@3.1.5" has unmet peer dependency "@types/react@^16.8.0".
warning " > react-apollo@3.1.5" has incorrect peer dependency "graphql@^14.3.1".
warning " > react-apollo@3.1.5" has unmet peer dependency "react-dom@^16.8.0".
warning "react-apollo > @apollo/react-hoc@3.1.5" has unmet peer dependency "@types/react@^16.8.0".
warning "react-apollo > @apollo/react-hoc@3.1.5" has incorrect peer dependency "graphql@^14.3.1".
warning "react-apollo > @apollo/react-hoc@3.1.5" has unmet peer dependency "react-dom@^16.8.0".
warning "react-apollo > @apollo/react-components@3.1.5" has unmet peer dependency "@types/react@^16.8.0".
warning "react-apollo > @apollo/react-components@3.1.5" has unmet peer dependency "apollo-cache@^1.3.2".
warning "react-apollo > @apollo/react-components@3.1.5" has unmet peer dependency "apollo-link@^1.2.12".
warning "react-apollo > @apollo/react-components@3.1.5" has unmet peer dependency "apollo-utilities@^1.3.2".
warning "react-apollo > @apollo/react-components@3.1.5" has incorrect peer dependency "graphql@^14.3.1".
warning "react-apollo > @apollo/react-components@3.1.5" has unmet peer dependency "react-dom@^16.8.0".
warning "react-apollo > @apollo/react-common@3.1.4" has unmet peer dependency "@types/react@^16.8.0".
warning "react-apollo > @apollo/react-common@3.1.4" has unmet peer dependency "apollo-utilities@^1.3.2".
warning "react-apollo > @apollo/react-common@3.1.4" has incorrect peer dependency "graphql@^14.3.1".
warning "react-apollo > @apollo/react-ssr@3.1.5" has unmet peer dependency "react-dom@^16.8.0".
warning "react-apollo > @apollo/react-hooks@3.1.5" has unmet peer dependency "@types/react@^16.8.0".
warning "react-apollo > @apollo/react-hooks@3.1.5" has incorrect peer dependency "graphql@^14.3.1".
warning "react-apollo > @apollo/react-hooks@3.1.5" has unmet peer dependency "react-dom@^16.8.0".
warning " > react-native-actionsheet@2.4.2" has unmet peer dependency "prop-types@>=15.4.0".
warning " > react-native-fs@2.18.0" has unmet peer dependency "react-native-windows@*".
warning " > react-native-in-app-notification@3.1.0" has unmet peer dependency "prop-types@^15.5.10".
warning "react-native-render-html > @native-html/transient-render-engine@9.2.2" has unmet peer dependency "@types/react-native@*".
warning "react-native-render-html > @native-html/transient-render-engine > @native-html/css-processor@1.10.2" has unmet peer dependency "@types/react@*".
warning "react-native-render-html > @native-html/transient-render-engine > @native-html/css-processor@1.10.2" has unmet peer dependency "@types/react-native@*".
warning " > react-native-webview@6.11.1" has incorrect peer dependency "react-native@>=0.57 <0.60".
warning "react-navigation > react-navigation-drawer@1.2.1" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "react-navigation > react-navigation-tabs@1.1.4" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "react-navigation > react-navigation-stack@1.4.0" has unmet peer dependency "react-native-screens@^1.0.0 || ^1.0.0-alpha".
warning "@react-native-community/eslint-config > eslint-plugin-react@7.12.4" has incorrect peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0".
warning "@react-native-community/eslint-config > eslint-plugin-react-native@3.6.0" has incorrect peer dependency "eslint@^3.17.0 || ^4 || ^5".
warning "@react-native-community/eslint-config > @typescript-eslint/eslint-plugin@1.13.0" has incorrect peer dependency "eslint@^5.0.0".
warning "@react-native-community/eslint-config > @typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning "@react-native-community/eslint-config > @typescript-eslint/parser@1.13.0" has incorrect peer dependency "eslint@^5.0.0".
[4/4] 🔨  Building fresh packages...
[1/3] ⠂ core-js
[2/3] ⠂ fsevents
error /Users/feegow/dev/feegow-app/node_modules/react-native-calendars: Command failed.
Exit code: 1
Command: node ./scripts/postinstall.js
Arguments: 
Directory: /Users/feegow/dev/feegow-app/node_modules/react-native-calendars
Output:
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/Users/feegow/dev/feegow-app/node_modules/react-native-calendars/scripts/postinstall.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []


feegow@MacBook-Pro-de-Feegow feegow-app % 
```

**Comment by sanjeedsawant** [comment]
Facing the same issue on 'npm install'

```
7095 info run react-native-calendars@1.1265.0 postinstall { code: 1, signal: null }
7096 info run core-js@2.6.12 postinstall { code: 0, signal: null }
7097 timing build:run:postinstall:node_modules/core-js Completed in 116ms
7098 info run react-native-unimodules@0.9.1 postinstall { code: 0, signal: null }
7099 timing build:run:postinstall:node_modules/react-native-unimodules Completed in 115ms
7100 info run react-native-elements@1.2.7 postinstall { code: 0, signal: null }
7101 timing build:run:postinstall:node_modules/react-native-elements Completed in 419ms
7102 info run clevertap-react-native@0.5.2 postinstall { code: 0, signal: null }
7103 timing build:run:postinstall:node_modules/clevertap-react-native Completed in 557ms
7104 timing reify:rollback:createSparse Completed in 7236ms
7105 timing reify:rollback:retireShallow Completed in 0ms
7106 timing command:install Completed in 147046ms
7107 verbose stack Error: command failed
7107 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
7107 verbose stack     at ChildProcess.emit (node:events:369:20)
7107 verbose stack     at maybeClose (node:internal/child_process:1067:16)
7107 verbose stack     at Socket.<anonymous> (node:internal/child_process:453:11)
7107 verbose stack     at Socket.emit (node:events:369:20)
7107 verbose stack     at Pipe.<anonymous> (node:net:665:12)
7108 verbose pkgid react-native-calendars@1.1265.0
7109 verbose cwd /Users/sanjeedsawant/Trunk/Papp-react
7110 verbose Darwin 20.6.0
7111 verbose argv "/usr/local/Cellar/node/15.13.0/bin/node" "/usr/local/bin/npm" "install" "--legacy-peer-deps"
7112 verbose node v15.13.0
7113 verbose npm  v7.7.6
7114 error code 1
7115 error path /Users/sanjeedsawant/Trunk/Papp-react/node_modules/react-native-calendars
7116 error command failed
7117 error command sh -c node ./scripts/postinstall.js
7118 error node:internal/modules/cjs/loader:927
7118 error   throw err;
7118 error   ^
7118 error
7118 error Error: Cannot find module '/Users/sanjeedsawant/Trunk/Papp-react/node_modules/react-native-calendars/scripts/postinstall.js'
7118 error     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
7118 error     at Function.Module._load (node:internal/modules/cjs/loader:769:27)
7118 error     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
7118 error     at node:internal/main/run_main_module:17:47 {
7118 error   code: 'MODULE_NOT_FOUND',
7118 error   requireStack: []
7118 error }
7119 verbose exit 1
```

**Comment by NouranFakhrEldeen** [comment]
@GustavoContreiras-Feegow did you find the solution? I am facing the same issue

**Comment by GustavoContreiras-Feegow** [comment]
> @GustavoContreiras-Feegow did you find the solution? I am facing the same issue 

yarn add react-native-calendars@1.1264.0

Error is on their repository and you are importing with ^ that updates it
