### ISSUE TITLE
 next react  error

### ISSUE THREAD

**Issue by 1729051657** [wix/react-native-calendars#1572]
![image](https://user-images.githubusercontent.com/33803388/125173378-951ce980-e1f1-11eb-83b2-c660a6276065.png)

error - ./node_modules/react-native-calendars/src/expandableCalendar/Context/Provider.js
Module parse failed: Unexpected token (19:21)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  */
| class CalendarProvider extends Component {
>   static displayName = 'CalendarProvider';
| 
|   static propTypes = {
event - build page: /next/dist/pages/_error
wait  - compiling...
error - ./node_modules/react-native-calendars/src/expandableCalendar/Context/Provider.js
Module parse failed: Unexpected token (19:21)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  */
| class CalendarProvider extends Component {
>   static displayName = 'CalendarProvider';
| 
|   static propTypes = {
/Users/kongdechao/Documents/webproject/TripFinder - React Next Hotel Template/TripFinder/packages/hotel-next/node_modules/react-native-calendars/src/index.js:1
export {default as Calendar} from './calendar';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:984:16)
    at Module._compile (internal/modules/cjs/loader.js:1032:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at eval (webpack-internal:///react-native-calendars:1:18)
    at Object.react-native-calendars (/Users/kongdechao/Documents/webproject/TripFinder - React Next Hotel Template/TripFinder/packages/hotel-next/.next/server/pages/post/[slug].js:1707:1)
    at __webpack_require__ (/Users/kongdechao/Documents/webproject/TripFinder - React Next Hotel Template/TripFinder/packages/hotel-next/.next/server/pages/post/[slug].js:23:31)
    at eval (webpack-internal:///./container/SinglePage/Reservation/RenderReservationForm.js:6:80)
    at Module../container/SinglePage/Reservation/RenderReservationForm.js (/Users/kongdechao/Documents/webproject/TripFinder - React Next Hotel Template/TripFinder/packages/hotel-next/.next/server/pages/post/[slug].js:1135:1)
    at __webpack_require__ (/Users/kongdechao/Documents/webproject/TripFinder - React Next Hotel Template/TripFinder/packages/hotel-next/.next/server/pages/post/[slug].js:23:31)
    at eval (webpack-internal:///./container/SinglePage/Reservation/Reservation.js:12:80)
    at Module../container/SinglePage/Reservation/Reservation.js (/Users/kongdechao/Documents/webproject/TripFinder - React Next Hotel Template/TripFinder/packages/hotel-next/.next/server/pages/post/[slug].js:1147:1)
    at __webpack_require__ (/Users/kongdechao/Documents/webproject/TripFinder - React Next Hotel Template/TripFinder/packages/hotel-next/.next/server/pages/post/[slug].js:23:31)

next react

**Comment by FrancisLeigh** [comment]
@1729051657 how did you get this calendar to work in nextJS ?
