### ISSUE TITLE
Importing react-native-calendar in workspace breaks tests in other workspace - Invariant Violation: __fbBatchedBridgeConfig is not set

### ISSUE THREAD

**Issue by boyanlevchev** [wix/react-native-calendars#1826]
## Description

So, hopefully I can clearly explain what's going on. I'm not sure if this is a bug, if it's already been resolved somewhere - but I can't find any information.

I am working on a large monorepo, with a number of workspaces in it. In workspace A I have added `react-native-calendars` and  tested it and it all works fine there. Weirdly though, when I import this module into a file in workspace A, it then breaks some of my tests in workspace B - which makes no direct reference (especially in the failing tests) to workspace A. 

### Current workaround
I managed to find a workaround by making a mock of `react-native-calendar` that returns `null` and setting it before any tests in workspace B run. But I would like to know why the issue is happening in the first place, and if there is something I missed in the set up that would help resolve this.

## Expected Behavior

I added `react-native-calendars` to workspace A in my monorepo - and I expect to be able to render it normally and test it normally - and this expectation is met.
I also expect that any unrelated projects would be untouched by these changes.

## Observed Behavior

Simply importing `react-native-calendars` and adding `<Calendar/>` component to the render method of my functional component in workspace A causes tests in workspace B to break.

This is the error I get when the tests fail (note this is in workspace B):

```
FAIL  src/screens/ExampleScreen/Example/__tests__/index.tsx
  ● Test suite failed to run

    Invariant Violation: __fbBatchedBridgeConfig is not set, cannot invoke native modules

      at invariant (../../ui/workspace_A/node_modules/invariant/invariant.js:40:15)
      at Object.<anonymous> (../../ui/workspace_A/node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:169:3)
      at Object.<anonymous> (../../ui/workspace_A/node_modules/react-native/Libraries/TurboModule/TurboModuleRegistry.js:13:23)
```

## Environment

Please run these commands in the project folder and fill in their results:

* `npm ls react-native-calendars`:
workspace_A@3.12.0 /Users/boyanlevchev/code/[redacted]/[redacted]/[redacted]/ui/workspace_A
└── react-native-calendars@1.1278.0 
workspace_B@0.0.1 /Users/boyanlevchev/code/[redacted]/[redacted]/[redacted]/apps/workspace_B
└── (empty)

* `npm ls react-native`:
Not sure why but this comes out empty in both workspaces.. version number in `package.json` of both workspaces is `^0.63.4`

* Testing suite:
"jest": "^26.6.3"
"@testing-library/jest-native": "^4.0.1",
"@testing-library/react-hooks": "^7.0.0",
"@testing-library/react-native": "^7.2.0",
"ts-jest": "^27.0.3",

Also specify:

1. Device/emulator/simulator & OS version:
* Breaking in tests locally:
    * System Version: macOS 11.4 (20F71)
    * Kernel Version: Darwin 20.5.0
* Breaking also on GitHub Actions

## Reproducible Demo

I will have to try and make one, as this is a hefty monorepo.

## Screenshots

No screenshots, all happening in testing.

**Comment by boyanlevchev** [comment]
Hi @kaur-karanbeer , I don’t know what the cause is - but I fixed it with the method described above.

Create a mock of the library before any tests that are breaking. You can set this globally in a jest config file too, so it’s mocked for the entire workspace.

to do this, please see https://jestjs.io/docs/jest-object#jestmockmodulename-factory-options
