### ISSUE TITLE
Error: undefined Unable to resolve module ./agenda

### ISSUE THREAD

**Issue by badgraphix** [wix/react-native-calendars#2160]
Please make our job easier by filling this template out to completion. If you're requesting a feature instead of reporting a bug, please feel free to skip the Environment and Reproducible Demo sections.

## Description

I have added the react-native-calendars module to a React Native project using the following command
`npm install --save react-native-calendars`

I go to a component that imports the react-native-calendars module and tries to render a <Calendar /> object.

## Expected Behavior

The Calendar component renders.

## Observed Behavior
 
I get the following error:

```
error: Error: Unable to resolve module ./agenda from C:\Users\badgr\dev\AndroidStudioProjects\my_app\node_modules\react-native-calendars\src\index.js:

None of these files exist:
  * node_modules\react-native-calendars\src\agenda(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules\react-native-calendars\src\agenda\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  1 | export {default as Calendar} from './calendar';
  2 | export {default as CalendarList} from './calendar-list';
> 3 | export {default as Agenda} from './agenda';
    |                                  ^
  4 | export {default as ExpandableCalendar} from './expandableCalendar';
  5 | export {default as AgendaList} from './expandableCalendar/agendaList';
  6 | export {default as Timeline} from './timeline/Timeline';
    at ModuleResolver.resolveDependency (C:\Users\badgr\dev\AndroidStudioProjects\my_app\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:136:15)
    at DependencyGraph.resolveDependency (C:\Users\badgr\dev\AndroidStudioProjects\my_app\node_modules\metro\src\node-haste\DependencyGraph.js:231:43)
    at Object.resolve (C:\Users\badgr\dev\AndroidStudioProjects\my_app\node_modules\metro\src\lib\transformHelpers.js:129:24)
    at resolve (C:\Users\badgr\dev\AndroidStudioProjects\my_app\node_modules\metro\src\DeltaBundler\traverseDependencies.js:396:33)
    at C:\Users\badgr\dev\AndroidStudioProjects\my_app\node_modules\metro\src\DeltaBundler\traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (C:\Users\badgr\dev\AndroidStudioProjects\my_app\node_modules\metro\src\DeltaBundler\traverseDependencies.js:411:33)
    at processModule (C:\Users\badgr\dev\AndroidStudioProjects\my_app\node_modules\metro\src\DeltaBundler\traverseDependencies.js:140:31)
    at async addDependency (C:\Users\badgr\dev\AndroidStudioProjects\my_app\node_modules\metro\src\DeltaBundler\traverseDependencies.js:230:18)
    at async Promise.all (index 0)
```

## Environment

* `npm ls react-native-calendars`: 
my_app@0.0.1 C:\Users\badgr\dev\AndroidStudioProjects\my_app
`-- react-native-calendars@1.1266.0

* `npm ls react-native`:
my_app@0.0.1 C:\Users\badgr\dev\AndroidStudioProjects\my_app
`-- react-native@0.68.2
  `-- @react-native-community/cli@7.0.4
    `-- react-native@0.68.2 deduped

1. Device/emulator/simulator & OS version:
I'm running this through Android Studio and its emulator, on an emulated Pixel phone.

**Comment by Labalabadie** [comment]
I have exact same error, didn´t find a solution yet

**Comment by curtisyuen** [comment]
Same error for me. Any advise to solving it please?
