### ISSUE TITLE
Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by system65** [wix/react-native-calendars#63]
Only after import it using `import { Calendar} from 'react-native-calendars; 

and it's shows (Cannot read property 'style' of undefined ) and totally stopped 

![simulator screen shot jun 17 2017 7 25 10 am](https://user-images.githubusercontent.com/5938616/27250114-76557a86-532e-11e7-8f8d-8bd569a019ac.png)

**Comment by tautvilas** [comment]
Did a clean install

`create-react-native-app CalendarsTryout`
`cd CalendarsTryout`
`npm install --save react-native-calendars`

added

`import { Calendar} from 'react-native-calendars'`
`npm run ios`

Did not get any error

**Comment by kcfgl** [comment]
For what its worth, I had this same issue. But upgrading RN to 0.44 sorted it out.

**Comment by joaosauer** [comment]
What I can do in case that I cannot update RN to 0.44? 
Any suggestions?

Thanks,
Joao

**Comment by tautvilas** [comment]
what version of RN are you using?

**Comment by joaosauer** [comment]
Hi, Thanks for the reply.
So, I was using 0.43.3
So, I just changed to:
"native-base": "^2.1.4",
"react": "^16.0.0-alpha.12",
"react-native": "^0.44.0",

And I have the fear that I should not have done it. :(
I'm now getting a new error in the node:
```
Looking for JS files in
   D:\Joao\git\F1Softwares\Code\Mobile


React packager ready.

Loading dependency graph, done.
error: bundling: UnableToResolveError: Unable to resolve module `react/lib/ReactPropTypes` from `D:\Joao\git\F1Softwares\Code\Mobile\node_modules\react-native\Libraries\Image\Image.android.js`: Module does not exist in the module map or in these directories:
  D:\Joao\git\F1Softwares\Code\Mobile\node_modules\react-native\node_modules\react\lib
,   D:\Joao\git\F1Softwares\Code\Mobile\node_modules\react\lib

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.
    at ResolutionRequest._resolveNodeDependency (D:/Joao/git/F1Softwares/Code/Mobile/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:394:11)
    at tryResolveSync (D:/Joao/git/F1Softwares/Code/Mobile/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:136:20)
    at tryResolveSync (D:/Joao/git/F1Softwares/Code/Mobile/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:66:12)
    at ResolutionRequest.resolveDependency (D:/Joao/git/F1Softwares/Code/Mobile/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:134:22)
    at dependencyNames.map.name (D:/Joao/git/F1Softwares/Code/Mobile/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:145:59)
    at Array.map (native)
    at ResolutionRequest.resolveModuleDependencies (D:/Joao/git/F1Softwares/Code/Mobile/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:145:42)
    at Promise.resolve.then (D:/Joao/git/F1Softwares/Code/Mobile/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:169:21)
    at process._tickCallback (internal/process/next_tick.js:103:7)
Bundling `index.android.js`  96.5% (786/800), failed.
```
Any idea what could be the problem?
I already deleted the node_modules and made a npm install and the problem is still persisting... :(

Thanks,
Joao

**Comment by joaosauer** [comment]
Ok, 
I was able to get it working now!
I have this in  my package.json:
```
"native-base": "^2.1.4",
"react": "^16.0.0-alpha.6",
"react-native": "^0.44.0",
 "react-native-calendars": "^1.4.0",
```

I also needed to make this command:
`npm install react@16.0.0-alpha.6 --save`

The line above was the most important part. Not sure if pointing out to the alpha.12 will still work, but I believe that will.
Correct me if I'm wrong, but I believe that doing --save will save the react to all projects and not just mine. I believe that this is what made the trick to get the error above being removed.

Thanks for your help!

Cheers,
Joao Sauer

**Comment by angularbaby** [comment]
Excuse me,`"react": "15.4.1",
    "react-native": "0.42.2",
    "react-native-calendars": "^1.4.0",`How can we support？thankyou！

**Comment by rockerrecruit** [comment]
Hey, I'm still having this problem:

`
Cannot read property 'style' of undefined
TypeError: Cannot read property 'style' of undefined
    at Module../node_modules/react-native-calendars/src/calendar/index.js (http://localhost:6006/vendors~app.b77b3c51f5ec6207931f.bundle.js:192876:24)
    at __webpack_require__ (http://localhost:6006/runtime~app.b77b3c51f5ec6207931f.bundle.js:849:30)
    at fn (http://localhost:6006/runtime~app.b77b3c51f5ec6207931f.bundle.js:151:20)
    at Module../node_modules/react-native-calendars/src/index.js (http://localhost:6006/vendors~app.b77b3c51f5ec6207931f.bundle.js:195434:67)
    at __webpack_require__ (http://localhost:6006/runtime~app.b77b3c51f5ec6207931f.bundle.js:849:30)
`

I tried looking at it myself but couldn't find a fix, any idea what it could be?
